---
title: "01 Basic R for Finance"
author: "Boni"
date: "9/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Basic

## Working with Matrix
We can create matrix from one atomic vector.
```{r}
x_vec <- c(9, 4, 6, 20, 19, 29)
x_mat <- matrix(data = x_vec, nrow = 2, ncol = 3, byrow = TRUE)
x_mat

cor(x_mat)
```

We can also create matrix from 2 vectors.
```{r}
y_vec = rnorm(6, 23, 98)

matrix_yx <- cbind(x_vec, y_vec)
matrix_yx

cor(matrix_yx)
```

## Working with DataFrame

```{r}
cash_flow <- rnorm(10, 4, 9)
year <- runif(10, 5, 45)
company <- c("Google", "Google", "Microsoft", "Microsoft", "Apple", "Apple", "Google", "Google", "Microsoft", "Microsoft")
company_data <- data.frame(company, cash_flow, year)
company_data

# sub-setting the DF
company_data[1:3,1, drop=FALSE]
company_data$cash_flow
subset(company_data, cash_flow < 6.00)

# Delete a column
company_data$year = NULL
company_data
```
## Working with Factor
```{r}
# Factor will make R treat string as integer.
investment <- c("stock", "bonds", "stock", "bonds", "stock")
investment_factor <- factor(investment)
# Summary of factor is more informative.
summary(investment)
summary(investment_factor)
# Change the levels.
investment
levels(investment) <- c("B", "S")
investment

# cut() will factoring the numbers based on interval.
price <- runif(100, 20, 100)
breaks <- c(0, 20, 40, 60, 80, 100)
grouped_price <- cut(price, breaks = breaks)
head(grouped_price)
levels(grouped_price) <- c("very_low", "low", "medium", "high", "very_high")
# Plot the factor
plot(grouped_price)

# Order factor
investment <- c("stock", "bonds", "stock", "bonds", "stock", "forex")
ranked_investment <- factor(investment, ordered = TRUE, levels = c("stock", "forex", "bonds"))
ranked_investment
plot(ranked_investment)
# To remove unavailable level after subset, use drop=TRUE
summary(ranked_investment[1:3, drop = TRUE])
```

*notes* R automatically treat string as factor, when using data.frame(), to remove this behavior we can add argument stringsAsFactors = FALSE.

## Working with List
```{r}
# List can contain multiple data type.
list1 <- list("Boni", investment)
list1
# To subset list we use [[]] instead of []
list1[[2]]
# Add names to list.
names(list1) <- c("name", "investment")
list1$name

# Split DataFrame to list
cash_flow <- rnorm(10, 4, 9)
year <- runif(10, 5, 45)
company <- c("Google", "Google", "Microsoft", "Microsoft", "Apple", "Apple", "Google", "Google", "Microsoft", "Microsoft")
company_data <- data.frame(company, cash_flow, year)
company_data

new_list <- split(company_data, company_data$company)
new_list

# Unsplit list
unsplit(new_list, company)

# Getting attributes
attributes(new_list)
attr(new_list, "names")
```

