---
title: "02-Intermediate-R-for-Finance"
author: "Boni"
date: "9/2/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Working with Date Time
```{r}
# Today
x <- Sys.Date()
y <- Sys.time()
x
y
class(x) # Calendar date class
class(y) # POSIX class, with POSIXct and POSIXlt

# Convert string to Date
date <- "2020-09-01" # Use the standard ISO 8601 Standard: year-month-day or year/month/day
date_as_date <- as.Date(date)
class(date_as_date)
as.numeric(date_as_date) # Find number of days since January 1, 1970

# Explicit conversion
as.Date("May 2020 09", format = "%b %Y %d")

# char_dates
char_dates <- c("1jan17", "2jan17", "3jan17", "4jan17", "5jan17")

# Create dates using as.Date() and the correct format 
dates <- as.Date(char_dates, format="%d%b%y")

# Use format() to go from "2017-01-04" -> "Jan 04, 17"
format(dates, format = "%b %d, %y")

# Use format() to go from "2017-01-04" -> "01,04,2017"
format(dates, format = "%m,%d,%Y")

# Dates
dates <- as.Date(c("2017-01-01", "2017-01-02", "2017-01-03"))

# Create the origin
origin <- as.Date("1970-01-01")

# Use as.numeric() on dates
as.numeric(dates)

# Find the difference between dates and origin
dates - origin
```
## Extract information from Date Time
```{r}
# dates
dates <- as.Date(c("2017-01-02", "2017-05-03", "2017-08-04", "2017-10-17"))

# Extract the months
months(dates)

# Extract the quarters
quarters(dates)

# dates2
dates2 <- as.Date(c("2017-01-02", "2017-01-03", "2017-01-04", "2017-01-05"))

# Assign the weekdays() of dates2 as the names()
names(dates2) <- weekdays(dates2)

# Print dates2
dates2
```

