---
title: "04 Importing and Managing Financial Data"
author: "Boni"
date: "9/3/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
```

# Use getSymbols()
```{r}
library(quantmod)
getSymbols(Symbols = "AAPL", src = "av", api.key = "0ST2PMQENLUXD5YT") 
# alphavantage 0ST2PMQENLUXD5YT
# src can be alphavantage (av), google, yahoo, fred
first(AAPL, 5)

getSymbols("GDP", src="FRED")
first(GDP, 5)

```

# Use Quandl()
```{r}
library(Quandl)
dgs10 <- Quandl::Quandl(code = "FRED/DGS10", type = "xts")
first(dgs10, 5)
```

# Get currency from Oanda
```{r}
# Get available currency in Oanda
head(quantmod::oanda.currencies)

# Create a currency_pair object
currency_pair <- "GBP/CAD"

# Load British Pound to Canadian Dollar exchange rate data
getSymbols(currency_pair, src = "oanda")

# Examine object using str()
str(GBPCAD)

# Try to load data from 190 days ago
getSymbols(currency_pair, from = Sys.Date() - 190, to = Sys.Date(), src = "oanda")
```

# Unemployment Rate from FRED
```{r}
# Create a series_name object
series_name <- "UNRATE"

# Load the data using getSymbols
getSymbols(series_name, src = "FRED", type = "xts")
head(UNRATE)

# Create a quandl_code object
quandl_code <- "FRED/UNRATE"

# Load the data using Quandl
unemploy_rate <- Quandl(quandl_code, type = "xts")
head(unemploy_rate)
```

# Extract OHLC
```{r}
# Important method to extract OHLC information: Op(), Hi(), Lo(), Cl(), Vo(), Ad(), and OHLC()
# Learn more: help("OHLC.Transformations")

# Get Symbols
getSymbols("TSLA", src = "yahoo", type = "xts")

# Extract the close column
tsla_close <- Cl(TSLA)

# Look at the head of dc_close
head(tsla_close)

# Extract the volume column
tsla_volume <- Vo(TSLA)

# Look at the head of dc_volume
head(tsla_volume)

# Extract the high, low, and close columns
tsla_hlc <- HLC(TSLA)

# Look at the head of dc_hlc
head(tsla_hlc)

# Extract the open, high, low, close, and volume columns
tsla_ohlcv <- OHLCV(TSLA)

# Look at the head of dc_ohlcv
head(tsla_ohlcv)

```

## Extract the Close column from many instruments

```{r}
Cl <- function (x) 
{
    if (has.Cl(x)) 
        return(x[, grep("Close", colnames(x), ignore.case = TRUE)])
    stop("subscript out of bounds: no column name containing \"Close\"")
}

# Symbols
symbols <- c("AAPL", "MSFT", "IBM")

# Create new environment
data_env <- new.env()

# Load symbols into data_env
getSymbols(symbols, env = data_env)

# Extract the close column from each object and combine into one xts object
close_data <- do.call(merge, eapply(data_env, Cl))

# View the head of close_data
head(close_data)
```

## Change default getSymbols()

```{r}
# Look at getSymbols.yahoo arguments
args(getSymbols.yahoo)

# Set default 'from' value for getSymbols.yahoo
setDefaults(getSymbols.yahoo, from = "2000-01-01")

# Confirm defaults were set correctly
getDefaults(name = "getSymbols.yahoo")
```

## Handling instrument symbols that clash or are not valid R names

```{r}
# get BRK-A
getSymbols("BRK-A")

# Assign the result to BRK.A
BRK.A <- get("BRK-A")

head(BRK.A)
```

## Another way to handle invalid names (1)

```{r}
# Create BRK.A object
BRK.A <- getSymbols("BRK-A", auto.assign = FALSE)

# Create col_names object with the column names of BRK.A
col_names <- colnames(BRK.A)

# Set BRK.A column names to syntactically valid names
colnames(BRK.A) <- make.names(col_names)

head(BRK.A)
```

## Another day to handle invalid names (2)

```{r}
# Set name for BRK-A to BRK.A
setSymbolLookup(BRK.A = list(name = "BRK-A"))

# Set name for T (AT&T) to ATT
setSymbolLookup(ATT = list(name = "T"))

# Load BRK.A and ATT data
getSymbols(c("BRK.A", "ATT"))
```

